### ISSUE TITLE
Add Julia to TeamCity

### ISSUE THREAD

**Issue by Hofer-Julian** [Deltares/Ribasim.jl#28]
In order to test Ribasim on TeamCity, we will want to have Julia preinstalled.
This will also simplify tests of other Julia-based products.

**Comment by Hofer-Julian** [comment]
> Minor point, but it might be a good idea to set `JULIA_CI` to `true` on TeamCity: https://docs.julialang.org/en/v1/manual/environment-variables/#JULIA_CI. Don't wanna juke the stats.

Seems like Julia can't make up their mind if they want true/false or 1/0 in their env vars :P

**Comment by visr** [comment]
Inside the language there is no truthy businesses, but for handling ENVs thats a different matter:

https://github.com/JuliaLang/julia/blob/681486dca9fa5aa011c736c0b617fe43d3bd2348/base/env.jl#L100

**Comment by Hofer-Julian** [comment]
> Minor point, but it might be a good idea to set JULIA_CI to true on TeamCity

Done
