### ISSUE TITLE
Deploy docs with CI

### ISSUE THREAD

**Issue by Hofer-Julian** [Deltares/Ribasim.jl#31]
Documentation is currently build and deployed from @visr's PC.
We should automize that and do that from GitHub Actions instead.

Depends on https://github.com/Deltares/Ribasim.jl/issues/30

**Comment by visr** [comment]
Currently the process to update the docs is:

1. run [demo.ipynb](https://github.com/Deltares/Ribasim.jl/blob/main/docs/demo.ipynb) (it currently needs updating)
2. `quarto publish gh-pages`

If the jupyter kernels are installed properly, we can also let quarto run the notebook for us.

Quarto documentation also has information on how to use it with GitHub Actions:

https://quarto.org/docs/websites/
https://quarto.org/docs/publishing/github-pages.html
https://github.blog/2022-08-10-github-pages-now-uses-actions-by-default/

**Comment by Hofer-Julian** [comment]
> If the jupyter kernels are installed properly, we can also let quarto run the notebook for us.

How long does it take at the moment to run [demo.ipynb](https://github.com/Deltares/Ribasim.jl/blob/main/docs/demo.ipynb)?
Is it feasible to run it every push on `main`?

Or should we instead check in the output to git?

**Comment by visr** [comment]
It should be feasible to run on every push to `main`, it doesn't take more than about 2 minutes.
