### ISSUE TITLE
Spelling it out

### ISSUE THREAD

**Issue by visr** [Deltares/Ribasim.jl#36]
Currently we are not using a mapping between internal variable names as the I/O names. That makes it more important to have clear names that are not too brief.

Connectors:
```
x -> flow
s -> storage

OutflowTable: upstream/downstream
Bifurcation: upstream/downstream_1/downstream_2
LevelLink: a-side/b-side
LevelControl and GeneralUser(_P): flow/storage
```

Variables:
```
S -> storage
C -> salinity
P -> precipitation
E_pot -> potential_evaporation
```

Profile:
```
volume -> storage
```

Bonus:
```
LSW -> Basin
```

Waterbalance:
```
location -> id
```

**Comment by gijsber** [comment]
Hi @visr would it not be more logical to call C concentration ?
