### ISSUE TITLE
Editing of GeoArrow is disabled in QGIS

### ISSUE THREAD

**Issue by Huite** [Deltares/Ribasim.jl#38]
The edit button cannot be clicked for a GeoArrow layer in QGIS, while the GDAL driver does seem to mention support for the create option: https://gdal.org/drivers/vector/arrow.html#vector-arrow

The same is true for (Geo)Parquet, the layers cannot be edited.

**Comment by Huite** [comment]
If my current understanding is correct, this may simply be a case that these formats haven't been added to the boilerplate of the  QGIS OGR provider. Of course it may be more complicated...

See: https://github.com/qgis/QGIS/issues/51165

**Comment by evetion** [comment]
Will be released in 3.28.3 (next patch release). If you use nightlies, it already works 🎉
